version: '3'

services:
  db:
    container_name: metrics-db
    image: postgres
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  db-test:
    container_name: metrics-db-test
    image: postgres
    restart: always
    ports:
      - '${TEST_DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
